services:
  - type: web
    name: vegmart
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE
        value: /var/data/vegmart.db
